// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package nosrabbitmq

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConsumer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) Close() *MockConsumer_Close_Call {
	return &MockConsumer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConsumer_Close_Call) Run(run func()) *MockConsumer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_Close_Call) Return(err error) *MockConsumer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumer_Close_Call) RunAndReturn(run func() error) *MockConsumer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionInfo provides a mock function for the type MockConsumer
func (_mock *MockConsumer) GetConnectionInfo() ConnectionInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionInfo")
	}

	var r0 ConnectionInfo
	if returnFunc, ok := ret.Get(0).(func() ConnectionInfo); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ConnectionInfo)
	}
	return r0
}

// MockConsumer_GetConnectionInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionInfo'
type MockConsumer_GetConnectionInfo_Call struct {
	*mock.Call
}

// GetConnectionInfo is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) GetConnectionInfo() *MockConsumer_GetConnectionInfo_Call {
	return &MockConsumer_GetConnectionInfo_Call{Call: _e.mock.On("GetConnectionInfo")}
}

func (_c *MockConsumer_GetConnectionInfo_Call) Run(run func()) *MockConsumer_GetConnectionInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_GetConnectionInfo_Call) Return(connectionInfo ConnectionInfo) *MockConsumer_GetConnectionInfo_Call {
	_c.Call.Return(connectionInfo)
	return _c
}

func (_c *MockConsumer_GetConnectionInfo_Call) RunAndReturn(run func() ConnectionInfo) *MockConsumer_GetConnectionInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetIdentifier provides a mock function for the type MockConsumer
func (_mock *MockConsumer) GetIdentifier() Identifier {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIdentifier")
	}

	var r0 Identifier
	if returnFunc, ok := ret.Get(0).(func() Identifier); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Identifier)
	}
	return r0
}

// MockConsumer_GetIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdentifier'
type MockConsumer_GetIdentifier_Call struct {
	*mock.Call
}

// GetIdentifier is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) GetIdentifier() *MockConsumer_GetIdentifier_Call {
	return &MockConsumer_GetIdentifier_Call{Call: _e.mock.On("GetIdentifier")}
}

func (_c *MockConsumer_GetIdentifier_Call) Run(run func()) *MockConsumer_GetIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_GetIdentifier_Call) Return(identifier Identifier) *MockConsumer_GetIdentifier_Call {
	_c.Call.Return(identifier)
	return _c
}

func (_c *MockConsumer_GetIdentifier_Call) RunAndReturn(run func() Identifier) *MockConsumer_GetIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// SetIdentifier provides a mock function for the type MockConsumer
func (_mock *MockConsumer) SetIdentifier(identifier Identifier) {
	_mock.Called(identifier)
	return
}

// MockConsumer_SetIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIdentifier'
type MockConsumer_SetIdentifier_Call struct {
	*mock.Call
}

// SetIdentifier is a helper method to define mock.On call
//   - identifier Identifier
func (_e *MockConsumer_Expecter) SetIdentifier(identifier interface{}) *MockConsumer_SetIdentifier_Call {
	return &MockConsumer_SetIdentifier_Call{Call: _e.mock.On("SetIdentifier", identifier)}
}

func (_c *MockConsumer_SetIdentifier_Call) Run(run func(identifier Identifier)) *MockConsumer_SetIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Identifier
		if args[0] != nil {
			arg0 = args[0].(Identifier)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumer_SetIdentifier_Call) Return() *MockConsumer_SetIdentifier_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsumer_SetIdentifier_Call) RunAndReturn(run func(identifier Identifier)) *MockConsumer_SetIdentifier_Call {
	_c.Run(run)
	return _c
}

// SetSignalChan provides a mock function for the type MockConsumer
func (_mock *MockConsumer) SetSignalChan(signalCh chan Signal) {
	_mock.Called(signalCh)
	return
}

// MockConsumer_SetSignalChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSignalChan'
type MockConsumer_SetSignalChan_Call struct {
	*mock.Call
}

// SetSignalChan is a helper method to define mock.On call
//   - signalCh chan Signal
func (_e *MockConsumer_Expecter) SetSignalChan(signalCh interface{}) *MockConsumer_SetSignalChan_Call {
	return &MockConsumer_SetSignalChan_Call{Call: _e.mock.On("SetSignalChan", signalCh)}
}

func (_c *MockConsumer_SetSignalChan_Call) Run(run func(signalCh chan Signal)) *MockConsumer_SetSignalChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan Signal
		if args[0] != nil {
			arg0 = args[0].(chan Signal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumer_SetSignalChan_Call) Return() *MockConsumer_SetSignalChan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsumer_SetSignalChan_Call) RunAndReturn(run func(signalCh chan Signal)) *MockConsumer_SetSignalChan_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Start(context1 context.Context) {
	_mock.Called(context1)
	return
}

// MockConsumer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockConsumer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockConsumer_Expecter) Start(context1 interface{}) *MockConsumer_Start_Call {
	return &MockConsumer_Start_Call{Call: _e.mock.On("Start", context1)}
}

func (_c *MockConsumer_Start_Call) Run(run func(context1 context.Context)) *MockConsumer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumer_Start_Call) Return() *MockConsumer_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsumer_Start_Call) RunAndReturn(run func(context1 context.Context)) *MockConsumer_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Stop(context1 context.Context) <-chan struct{} {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan struct{}); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockConsumer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockConsumer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockConsumer_Expecter) Stop(context1 interface{}) *MockConsumer_Stop_Call {
	return &MockConsumer_Stop_Call{Call: _e.mock.On("Stop", context1)}
}

func (_c *MockConsumer_Stop_Call) Run(run func(context1 context.Context)) *MockConsumer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumer_Stop_Call) Return(valCh <-chan struct{}) *MockConsumer_Stop_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockConsumer_Stop_Call) RunAndReturn(run func(context1 context.Context) <-chan struct{}) *MockConsumer_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRabbitMQManager creates a new instance of MockIRabbitMQManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRabbitMQManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRabbitMQManager {
	mock := &MockIRabbitMQManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRabbitMQManager is an autogenerated mock type for the IRabbitMQManager type
type MockIRabbitMQManager struct {
	mock.Mock
}

type MockIRabbitMQManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRabbitMQManager) EXPECT() *MockIRabbitMQManager_Expecter {
	return &MockIRabbitMQManager_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockIRabbitMQManager
func (_mock *MockIRabbitMQManager) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRabbitMQManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIRabbitMQManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIRabbitMQManager_Expecter) Close() *MockIRabbitMQManager_Close_Call {
	return &MockIRabbitMQManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIRabbitMQManager_Close_Call) Run(run func()) *MockIRabbitMQManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRabbitMQManager_Close_Call) Return(err error) *MockIRabbitMQManager_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRabbitMQManager_Close_Call) RunAndReturn(run func() error) *MockIRabbitMQManager_Close_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterConsumer provides a mock function for the type MockIRabbitMQManager
func (_mock *MockIRabbitMQManager) RegisterConsumer(ctx context.Context, factory ...ConsumerFactory) error {
	var tmpRet mock.Arguments
	if len(factory) > 0 {
		tmpRet = _mock.Called(ctx, factory)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RegisterConsumer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...ConsumerFactory) error); ok {
		r0 = returnFunc(ctx, factory...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRabbitMQManager_RegisterConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterConsumer'
type MockIRabbitMQManager_RegisterConsumer_Call struct {
	*mock.Call
}

// RegisterConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - factory ...ConsumerFactory
func (_e *MockIRabbitMQManager_Expecter) RegisterConsumer(ctx interface{}, factory ...interface{}) *MockIRabbitMQManager_RegisterConsumer_Call {
	return &MockIRabbitMQManager_RegisterConsumer_Call{Call: _e.mock.On("RegisterConsumer",
		append([]interface{}{ctx}, factory...)...)}
}

func (_c *MockIRabbitMQManager_RegisterConsumer_Call) Run(run func(ctx context.Context, factory ...ConsumerFactory)) *MockIRabbitMQManager_RegisterConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []ConsumerFactory
		var variadicArgs []ConsumerFactory
		if len(args) > 1 {
			variadicArgs = args[1].([]ConsumerFactory)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIRabbitMQManager_RegisterConsumer_Call) Return(err error) *MockIRabbitMQManager_RegisterConsumer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRabbitMQManager_RegisterConsumer_Call) RunAndReturn(run func(ctx context.Context, factory ...ConsumerFactory) error) *MockIRabbitMQManager_RegisterConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockIRabbitMQManager
func (_mock *MockIRabbitMQManager) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRabbitMQManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIRabbitMQManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockIRabbitMQManager_Expecter) Start() *MockIRabbitMQManager_Start_Call {
	return &MockIRabbitMQManager_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockIRabbitMQManager_Start_Call) Run(run func()) *MockIRabbitMQManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRabbitMQManager_Start_Call) Return(err error) *MockIRabbitMQManager_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRabbitMQManager_Start_Call) RunAndReturn(run func() error) *MockIRabbitMQManager_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockIRabbitMQManager
func (_mock *MockIRabbitMQManager) Stop(ctx context.Context) <-chan struct{} {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan struct{}); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockIRabbitMQManager_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockIRabbitMQManager_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRabbitMQManager_Expecter) Stop(ctx interface{}) *MockIRabbitMQManager_Stop_Call {
	return &MockIRabbitMQManager_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockIRabbitMQManager_Stop_Call) Run(run func(ctx context.Context)) *MockIRabbitMQManager_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRabbitMQManager_Stop_Call) Return(valCh <-chan struct{}) *MockIRabbitMQManager_Stop_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockIRabbitMQManager_Stop_Call) RunAndReturn(run func(ctx context.Context) <-chan struct{}) *MockIRabbitMQManager_Stop_Call {
	_c.Call.Return(run)
	return _c
}
